#!/bin/sh
input() {
	cd $1
	input=$1
}
use() {
	echo task log:
	echo "--> "For input "[$input] use:"
	echo "-->	"Sorting to $path:
	echo "-->		"Using: $@ 
	for item in $@
	do
		mv "$item" "$path"
	done
}
. ~/.config/sortfs/sortfs.conf
